### ISSUE TITLE
Master won't build with JDK 11.0.15

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel#383]
```
com.oracle.svm.jni.hosted.JNIFeature]
[loading /modules/java.base/java/lang/invoke/MethodHandles.class]
/home/tester/jenkins/workspace/mandrel-master-linux-build-matrix/JDK_RELEASE/ga/JDK_VERSION/11/LABEL/el8_aarch64/mandrel/substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/meta/SubstrateInstalledCodeImpl.java:67: error: getAddress() in SubstrateInstalledCodeImpl cannot override getAddress() in InstalledCode
    public long getAddress() {
                ^
  overridden method is final
/home/tester/jenkins/workspace/mandrel-master-linux-build-matrix/JDK_RELEASE/ga/JDK_VERSION/11/LABEL/el8_aarch64/mandrel/substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal
```

Log: https://ci.modcluster.io/job/mandrel-master-linux-build-matrix/212/JDK_RELEASE=ga,JDK_VERSION=11,LABEL=el8_aarch64/consoleText

**Comment by Karm** [comment]
Perhaps Jenkins CI thing. The job has been down for some time due to missing python update.

**Comment by jerboaa** [comment]
This is a duplicate of #373
