### PR TITLE
Account for JDK-8236867: Enhance Graal interface handling

### PR DESCRIPTION
**Pull request by jerboaa**
This fixes the build with latest OpenJDK 11.0.8-ga. See this change which makes it necessary to account for it in Graal VM land:
http://hg.openjdk.java.net/jdk-updates/jdk11u/rev/76890092b5ca

I'm going to try to get this into upstream Graal VM as well.

### CODE REVIEW

**Comment by jerboaa** [comment]
Note that the failing tests are expected and due to it using an older OpenJDK, which isn't out yet. Work in progress.

**Comment by Karm** [comment]
@jerboaa While I can build and run Mandrel with the patch (including a small Quarkus app), it fails to build the whole Graal for me.

```
Compiling org.graalvm.compiler.truffle.test with javac-daemon(JDK 11)... [dependency TRUFFLE_TEST updated]
Building libjvmcicompiler.so.image... [dependency GRAAL_HOTSPOT_LIBRARY updated]
[libjvmcicompiler:3089]    classlist:   2,977.04 ms,  0.96 GB
[libjvmcicompiler:3089]        setup:     119.40 ms,  0.96 GB
Fatal error:java.lang.InternalError: java.lang.InternalError: LibGraalFeature is not supported by the current JDK
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:463)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:359)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:518)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:117)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:547)
Caused by: java.lang.InternalError: LibGraalFeature is not supported by the current JDK
	at com.oracle.svm.graal.hotspot.libgraal.LibGraalFeature.isInConfiguration(LibGraalFeature.java:152)
	at com.oracle.svm.hosted.FeatureHandler.registerFeature(FeatureHandler.java:162)
	at com.oracle.svm.hosted.FeatureHandler.registerFeatures(FeatureHandler.java:125)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:823)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:536)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1

Building libjvmcicompiler.so.image failed
1 build tasks failed

Traceback (most recent call last):
  File "/home/karm/workspaceRH/graal/mx/mx_gate.py", line 416, in gate
    _run_gate(cleanArgs, args, tasks)
  File "/home/karm/workspaceRH/graal/mx/mx_gate.py", line 619, in _run_gate
    runner(args, tasks)
  File "/home/karm/workspaceRH/graal/graal/substratevm/mx.substratevm/mx_substratevm.py", line 458, in svm_gate_body
    build_native_image_image()
  File "/home/karm/workspaceRH/graal/graal/substratevm/mx.substratevm/mx_substratevm.py", line 348, in build_native_image_image
    _mx_vm(['build'] + (args or []), config, env=env)
  File "/home/karm/workspaceRH/graal/graal/substratevm/mx.substratevm/mx_substratevm.py", line 293, in _mx_vm
    return mx.run_mx(config.mx_args() + args, suite=_vm_suite_dir(), nonZeroIsFatal=nonZeroIsFatal, out=out, err=err, timeout=timeout, env=env, quiet=quiet)
  File "/home/karm/workspaceRH/graal/mx/mx.py", line 12432, in run_mx
    return run(commands + args, nonZeroIsFatal=nonZeroIsFatal, out=out, err=err, timeout=timeout, env=env, cwd=cwd)
  File "/home/karm/workspaceRH/graal/mx/mx.py", line 12634, in run
    abort(retcode)
  File "/home/karm/workspaceRH/graal/mx/mx.py", line 3879, in abort
    raise SystemExit(error_code)
SystemExit: 1

The sequence of mx commands that were executed until the failure follows:

mx --primary-suite-path /home/karm/workspaceRH/graal/graal/substratevm --J @-Xmx4g --java-home=/var/X/JDKs/java-11-openjdk-11.0.8.10-0.vanilla.20200714.el7.x86_64 version --oneline
mx --primary-suite-path /home/karm/workspaceRH/graal/graal/substratevm --J @-Xmx4g --java-home=/var/X/JDKs/java-11-openjdk-11.0.8.10-0.vanilla.20200714.el7.x86_64 sversions
mx --primary-suite-path /home/karm/workspaceRH/graal/graal/substratevm --J @-Xmx4g --java-home=/var/X/JDKs/java-11-openjdk-11.0.8.10-0.vanilla.20200714.el7.x86_64 verifymultireleaseprojects
mx --primary-suite-path /home/karm/workspaceRH/graal/graal/substratevm --J @-Xmx4g --java-home=/var/X/JDKs/java-11-openjdk-11.0.8.10-0.vanilla.20200714.el7.x86_64 clean --all
mx --primary-suite-path /home/karm/workspaceRH/graal/graal/substratevm --J @-Xmx4g --java-home=/var/X/JDKs/java-11-openjdk-11.0.8.10-0.vanilla.20200714.el7.x86_64 build -p --warning-as-error --force-javac
mx --primary-suite-path /home/karm/workspaceRH/graal/graal/substratevm --J @-Xmx4g --java-home=/var/X/JDKs/java-11-openjdk-11.0.8.10-0.vanilla.20200714.el7.x86_64 ideclean
mx --primary-suite-path /home/karm/workspaceRH/graal/graal/substratevm --J @-Xmx4g --java-home=/var/X/JDKs/java-11-openjdk-11.0.8.10-0.vanilla.20200714.el7.x86_64 ideinit
mx --primary-suite-path /home/karm/workspaceRH/graal/graal/substratevm --J @-Xmx4g --java-home=/var/X/JDKs/java-11-openjdk-11.0.8.10-0.vanilla.20200714.el7.x86_64 spotbugs
mx --primary-suite-path /home/karm/workspaceRH/graal/graal/substratevm --J @-Xmx4g --java-home=/var/X/JDKs/java-11-openjdk-11.0.8.10-0.vanilla.20200714.el7.x86_64 verifylibraryurls

If the previous sequence is incomplete or some commands were executed programmatically use:

mx --primary-suite-path /home/karm/workspaceRH/graal/graal/substratevm --J @-Xmx4g --java-home=/var/X/JDKs/java-11-openjdk-11.0.8.10-0.vanilla.20200714.el7.x86_64 gate --strict-mode --tags fullbuild
```

**Comment by jerboaa** [comment]
@Karm I've never tried to build libgraal. Did this ever work?

**Comment by Karm** [comment]
@jerboaa Indeed it works...with labsjdk-ce-11 current master c275864 build:

```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-jvmci-20.2-b03)
OpenJDK 64-Bit Server VM (build 11.0.7+10-jvmci-20.2-b03, mixed mode)
2020-07-15 10:23:49 [62.9GB of 713.1GB free]: --- Build Succeeded ---
2020-07-15 10:23:49 [62.9GB of 713.1GB free]: JDK bundle: /var/X/JDKs/labs-openjdk-11/build/labsjdks/release/labsjdk-ce-11.0.7+10-jvmci-20.2-b03-linux-amd64.tar.gz [182.2MB]
2020-07-15 10:23:49 [62.9GB of 713.1GB free]: Symbols bundle: /var/X/JDKs/labs-openjdk-11/build/labsjdks/release/labsjdk-ce-11.0.7+10-jvmci-20.2-b03-linux-amd64.symbols.tar.gz [116.2MB]
2020-07-15 10:23:49 [62.9GB of 713.1GB free]: Total build time: 0:11:05.754152
```
  
Then used to compile **compiler** and **substratevm** on the current Mandrel mandrel/20.1 branch, HEAD beb2fd6:

```
$ mx --primary-suite-path /home/karm/workspaceRH/graal/graal/compiler --J @-Xmx4g --java-home=/var/X/JDKs/labs-openjdk-11/build/labsjdks/release/labsjdk-ce-11.0.7-jvmci-20.2-b03 gate --strict-mode --tags fullbuild
```

```
$ mx --primary-suite-path /home/karm/workspaceRH/graal/graal/substratevm --J @-Xmx4g --java-home=/var/X/JDKs/labs-openjdk-11/build/labsjdks/release/labsjdk-ce-11.0.7-jvmci-20.2-b03 gate --strict-mode --tags fullbuild
```
 
```
$ /home/karm/workspaceRH/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_865E91DFC2_JAVA11/graalvm-865e91dfc2-java11-20.1.0/bin/native-image --version
GraalVM Version 20.1.0 (Java Version 11.0.7)
```
   
Although I don't know how many other things would have to be changed/patched for it to work with JDK 11.0.8 (note the Lab's JDK 11 master is still 11.0.7).  All in all, it is unlikely related to this patch after all...IMHO.

**Comment by jerboaa** [comment]
> @jerboaa Indeed it works...with labsjdk-ce-11 current master c275864 build:
> 
> ```
> openjdk version "11.0.7" 2020-04-14
> OpenJDK Runtime Environment (build 11.0.7+10-jvmci-20.2-b03)
> OpenJDK 64-Bit Server VM (build 11.0.7+10-jvmci-20.2-b03, mixed mode)
> ```

Right. With labs JDK. We don't have any of the libgraal changes in OpenJDK. So correction: "Did this ever work with OpenJDK?" :-)
...

> Although I don't know how many other things would have to be changed/patched for it to work with JDK 11.0.8 (note the Lab's JDK 11 master is still 11.0.7). All in all, it is unlikely related to this patch after all...IMHO.

I'm pretty sure it's unrelated.

**Comment by Karm** [comment]
> Right. With labs JDK. We don't have any of the libgraal changes in OpenJDK. So correction: "Did this ever work with OpenJDK?" :-)

I don't think it has.

So this patch works just fine in my book; both with a simple app and now also with a good portion of Quarkus Native TS  (the rest is still running).

**Comment by zakkak** [comment]
I am wondering whether we can afford waiting for the upstream patch mentioned in https://github.com/oracle/graal/issues/2676

Regarding the patch it fails with on github CI:
```
/home/runner/work/mandrel/mandrel/substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/infrastructure/WrappedConstantPool.java:162: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/runner/work/mandrel/mandrel/substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/infrastructure/WrappedConstantPool.java:167: error: cannot find symbol
            return wrapped.lookupReferencedType(cpi, opcode);
                          ^
  symbol:   method lookupReferencedType(int,int)
  location: variable wrapped of type ConstantPool
2 errors
```

**Comment by Karm** [comment]
@zakkak Well, it is bound to fail, because it doesn't run with the patched JDK...  We would need 11.0.8+10 in the GitHub CI.

**Comment by zakkak** [comment]
> @zakkak Well, it is bound to fail, because it doesn't run with the patched JDK... We would need 11.0.8+10 in the GitHub CI.

Then the PR needs to include this change as well before being merged :)

**Comment by jerboaa** [comment]
> > @zakkak Well, it is bound to fail, because it doesn't run with the patched JDK... We would need 11.0.8+10 in the GitHub CI.
> 
> Then the PR needs to include this change as well before being merged :)

Let me do that then. Thanks!

**Comment by jerboaa** [comment]
Building quarkus now failed with (when trying to dowload from the maven repo):
```
Caused by: javax.net.ssl.SSLException: Connection timed out (Read failed)
```

File: compiler/src/org.graalvm.compiler.serviceprovider.jdk8/src/org/graalvm/compiler/serviceprovider/GraalServices.java [hunk 1]
```diff
@@ -449,4 +451,12 @@ public static int getJavaUpdateVersion() {
         }
         return Integer.parseInt(matcher.group(1));
     }
+
```
Comment (zakkak) [inline compiler/src/org.graalvm.compiler.serviceprovider.jdk8/src/org/graalvm/compiler/serviceprovider/GraalServices.java:454]:
```suggestion

    @SuppressWarnings("unused")
```

File: compiler/src/org.graalvm.compiler.serviceprovider/src/org/graalvm/compiler/serviceprovider/GraalServices.java [hunk 2]
```diff
@@ -253,4 +255,13 @@ public static VirtualObject createVirtualObject(ResolvedJavaType type, int id, b
     public static int getJavaUpdateVersion() {
         throw shouldNotReachHere();
     }
+
```
Comment (zakkak) [inline compiler/src/org.graalvm.compiler.serviceprovider/src/org/graalvm/compiler/serviceprovider/GraalServices.java:258]:
```suggestion

    @SuppressWarnings("unused")
```

**Comment by jerboaa** [comment]
Thanks. I'll merge this tomorrow.

**Comment by zakkak** [comment]
@jerboaa before merging please have a look at https://github.com/graalvm/mandrel/pull/79 and choose the best one :)

**Comment by Karm** [comment]
@zakkak @jerboaa    Severin's branch jerboaa:JDK-8236867-fix built [here](https://ci.modcluster.io/view/Mandrel/job/mandrel-linux-build/63/) looks good to me, full Quarkus Native TS run on Centos 8:

https://ci.modcluster.io/view/Mandrel/job/mandrel-linux-test/OS_AXIS=centos8/60/testReport/

**Comment by jerboaa** [comment]
> @jerboaa before merging please have a look at #79 and choose the best one :)

Let's go with #79
