### PR TITLE
[23.1] Backport: Minor JNI and libchelper fixes

### PR DESCRIPTION
**Pull request by zakkak**
Backport of https://github.com/oracle/graal/pull/7955

- **Fix missing headers in libchelper.**
- **Fix potentially pending JNI exceptions.**

Resolves build issues like:

```
[7/10] CC src/getThreadId.o
FAILED: src/getThreadId.o 
gcc -MMD -MF src/getThreadId.o.d -I/home/zakkak/code/mandrel/substratevm/src/com.oracle.svm.native.libchelper/include  -fdebug-prefix-map=/home/zakkak/code/mandrel=mandrel -fdebug-prefix-map=/home/zakkak/code/mandrel/substratevm/mxbuild/jdk21=jdk21 -fdebug-prefix-map=/home/zakkak/jvms/jdk-21.0.4+2=jdk-21.0.4+2 -gno-record-gcc-switches -g -gdwarf-4 -fPIC -O2 -D_LITTLE_ENDIAN -ffunction-sections -fdata-sections -fvisibility=hidden -D_FORTIFY_SOURCE=0 -c /home/zakkak/code/mandrel/substratevm/src/com.oracle.svm.native.libchelper/src/getThreadId.c -o src/getThreadId.o
/home/zakkak/code/mandrel/substratevm/src/com.oracle.svm.native.libchelper/src/getThreadId.c: In function ‘getThreadId’:
/home/zakkak/code/mandrel/substratevm/src/com.oracle.svm.native.libchelper/src/getThreadId.c:39:17: error: implicit declaration of function ‘syscall’ [-Wimplicit-function-declaration]
   39 |   return (pid_t)syscall(SYS_gettid);
      |                 ^~~~~~~
ninja: build stopped: subcommand failed.
, -2)
```

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]

**Comment by jerboaa** [comment]
Two failing checks are due to https://github.com/graalvm/mandrel/issues/732. I guess we should investigate a fix for this or see passing checks with `21.0.3` (JDK 21 GA).

**Comment by zakkak** [comment]
> Two failing checks are due to #732. I guess we should investigate a fix for this

I plan to do this in another PR

> or see passing checks with `21.0.3` (JDK 21 GA).

I scheduled https://github.com/graalvm/mandrel/actions/runs/9179917652

**Comment by zakkak** [comment]
> I scheduled https://github.com/graalvm/mandrel/actions/runs/9179917652

CI looks good. Merging.
