### ISSUE TITLE
Mandrel master native-image fails: JVMCIError: VM config values missing that should be present in JDK 11 linux-amd64

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel#37]
Hello,

While our **20.1** branch :heavy_check_mark: works fine, Mandrel **master**'s branch :x: native-image fails to build even a rudimentary program. 

## Steps to reproduce

```
#!/bin/sh

export MAVEN_REPO=${HOME}/.m2/repository
export MANDREL_REPO=/home/karm/workspaceRH/graal/graal
export JAVA_HOME=/var/X/JDKs/openjdk-11.0.8+4
export MANDREL_JDK=/home/karm/workspaceRH/mandrel-packaging/mandrelJDK
export MANDREL_HOME=/home/karm/workspaceRH/mandrel-packaging/mandrelJDK
export MX_HOME=/home/karm/workspaceRH/graal/mx
export M2_HOME=/home/karm/Tools/apache-maven-3.6.3
export PATH=${JAVA_HOME}/bin:${M2_HOME}/bin:${MX_HOME}:${PATH}
./buildJDK.sh
if [[ ! -e "${MANDREL_HOME}/bin/native-image" ]]; then
  echo "Cannot find native-image tool. Quitting..."
  exit 1
fi

cat >./Hello.java <<EOL
public class Hello {
public static void main(String[] args) {
    System.out.println("Hello.");
}
}
EOL
export JAVA_HOME=${MANDREL_HOME}
export PATH=${JAVA_HOME}/bin:${PATH}
javac Hello.java
native-image Hello
if [[ "`./hello`" == "Hello." ]]; then echo Done; else echo Native image fail;exit 1;fi

```

## Failure

```
    Exception in thread "main" jdk.vm.ci.common.JVMCIError: VM config values missing that should be present in JDK 11 linux-amd64 (java.home=/home/karm/workspaceRH/mandrel-packaging/mandrelJDK, java.vm.name=OpenJDK 64-Bit Server VM, java.vm.version=11.0.8-ea+4):
    CodeInstaller::FRAME_COMPLETE at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.GraalHotSpotVMConfig.<init>(GraalHotSpotVMConfig.java:889)
    at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.GraalHotSpotVMConfigAccess.reportErrors(GraalHotSpotVMConfigAccess.java:226)
    at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.GraalHotSpotVMConfig.<init>(GraalHotSpotVMConfig.java:66)
    at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalRuntime.<init>(HotSpotGraalRuntime.java:163)
    at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:156)
    at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:134)
    at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:52)
    at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.getCompiler(HotSpotJVMCIRuntime.java:425)
    at com.oracle.svm.hosted.c.GraalAccess.getGraalCapability(GraalAccess.java:50)
    at com.oracle.svm.hosted.c.GraalAccess.getOriginalTarget(GraalAccess.java:38)
    at com.oracle.svm.hosted.NativeImageGeneratorRunner.isValidArchitecture(NativeImageGeneratorRunner.java:208)
    at com.oracle.svm.hosted.NativeImageGeneratorRunner.verifyValidJavaVersionAndPlatform(NativeImageGeneratorRunner.java:413)
    at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:219)
    at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:505)
    at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:114)
    at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:534)
```

## Versions
 * Mandrel master, 9c527d0
 * OpenJDK 11.0.8+4 ea

**Comment by Karm** [comment]
I understand that the focus is 20.1 branch, yet I think it's pertinent to keep this around to remind that master is not ready...

**Comment by zakkak** [comment]
That's interesting!

This issue should be resolved on master by https://github.com/oracle/graal/commit/24a764e4a9afe8b6a867ac11ed44da98c890931b per https://github.com/oracle/graal/issues/2515

I will have a look, thanks for reporting this

**Comment by Karm** [comment]
@zakkak  It was caught by Jenkins build that was running master instead of 20.1    Will set it up to run both.

**Comment by zakkak** [comment]
@Karm it seems to work fine with JDK 11.0.8+7 ea can you please confirm and close this issue?

**Comment by Karm** [comment]
@zakkak Build with 11.0.8+8:

:x: https://ci.modcluster.io/job/mandrel-master-linux-build/1/consoleText 

```
15:09:25 /home/jenkins/jenkins/workspace/mandrel-master-linux-build/mandrel/substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/meta/AnalysisType.java:1014: error: method does not override or implement a method from a supertype
15:09:25     @Override
15:09:25     ^
15:09:25 /home/jenkins/jenkins/workspace/mandrel-master-linux-build/mandrel/substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/meta/AnalysisType.java:1016: error: cannot find symbol
15:09:25         wrapped.link();
15:09:25                ^
15:09:25   symbol:   method link()
15:09:25   location: variable wrapped of type ResolvedJavaType
15:09:25 /home/jenkins/jenkins/workspace/mandrel-master-linux-build/mandrel/substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/meta/AnalysisType.java:1019: error: method does not override or implement a method from a supertype
15:09:25     @Override
15:09:25     ^
15:09:25 /home/jenkins/jenkins/workspace/mandrel-master-linux-build/mandrel/substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/meta/AnalysisType.java:1021: error: cannot find symbol
15:09:25         return wrapped.hasDefaultMethods();
15:09:25                       ^
15:09:25   symbol:   method hasDefaultMethods()
15:09:25   location: variable wrapped of type ResolvedJavaType
15:09:25 /home/jenkins/jenkins/workspace/mandrel-master-linux-build/mandrel/substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/meta/AnalysisType.java:1024: error: method does not override or implement a method from a supertype
15:09:25     @Override
15:09:25     ^
15:09:25 /home/jenkins/jenkins/workspace/mandrel-master-linux-build/mandrel/substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/meta/AnalysisType.java:1026: error: cannot find symbol
15:09:25         return wrapped.declaresDefaultMethods();
15:09:25                       ^
15:09:25   symbol:   method declaresDefaultMethods()
15:09:25   location: variable wrapped of type ResolvedJavaType
15:09:25 6 errors
15:09:25 
15:09:29 Note: /home/jenkins/jenkins/workspace/mandrel-master-linux-build/mandrel/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JavaLangSubstitutions.java uses or overrides a deprecated API that is marked for removal.
15:09:29 Note: Recompile with -Xlint:removal for details.
15:09:29 Compiling com.oracle.graal.pointsto with javac-daemon(JDK 11) failed
15:09:29 1 build tasks failed
15:09:29 Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
15:09:29 	at OperatingSystem.exec(build.java:1189)
15:09:29 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
15:09:29 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
15:09:29 	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
15:09:29 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
15:09:29 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
15:09:29 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
15:09:29 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
15:09:29 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
15:09:29 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
15:09:29 	at Mx.build(build.java:435)
15:09:29 	at SequentialBuild.build(build.java:249)
15:09:29 	at build.main(build.java:42)
15:09:29 Caused by: java.lang.RuntimeException: Failed, exit code: 1
15:09:29 	at OperatingSystem.exec(build.java:1183)
15:09:29 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
15:09:29 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
15:09:29 	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
15:09:29 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
15:09:29 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
15:09:29 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
15:09:29 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
15:09:29 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
15:09:29 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
15:09:29 	at Mx.build(build.java:435)
15:09:29 	at SequentialBuild.build(build.java:249)
15:09:29 	at build.main(build.java:42)
15:09:29 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:09:29 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:09:29 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:09:29 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
15:09:29 	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:404)
15:09:29 	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:179)
15:09:29 	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:119)
15:09:29 Build step 'Execute shell' marked build as failure
```

**Comment by zakkak** [comment]
This is a different issue and we need to backport https://bugs.openjdk.java.net/browse/JDK-8247246 to upstream jdk11 to get this fixed (see https://github.com/oracle/graal/issues/2628).

**Comment by zakkak** [comment]
Backport is now merged in jdk11u https://bugs.openjdk.java.net/browse/JDK-8249047

**Comment by zakkak** [comment]
`graal/master` builds with OpenJDK 11.0.9-ea+1
https://github.com/graalvm/mandrel/runs/977811823?check_suite_focus=true
